[package]
name = "day_19"
version = "0.1.0"
authors = ["Joey Hines <joey@ahines.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_helper = { path = "../aoc_helper" }
itertools = "0.9.0"
regex = "1.4.2"