[package]
name = "day_4"
version = "0.1.0"
authors = ["Joey Hines <joey.ahines@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
itertools = "0.9.0"
aoc_helper = { path = "../aoc_helper"}